import {POST, UPDATE_PROFILE, UPDATE_PASSWORD} from "utils/fetchHelper";

export const GET_PROFILE_BEGIN = 'GET_PROFILE_BEGIN';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const UPDATE_PASSWORD_BEGIN = 'UPDATE_PASSWORD_BEGIN';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';

export const LOCAL_PROFILE_UPDATE = 'LOCAL_PROFILE_UPDATE';

export function getProfile(url, data) {
  return POST(url, data, GET_PROFILE_BEGIN, GET_PROFILE_SUCCESS, GET_PROFILE_ERROR);
}

export function updateProfile(URL, data) {
 return UPDATE_PROFILE(URL, data, UPDATE_PROFILE_BEGIN, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_ERROR);
}

export function updatePassword(URL, data) {
  return UPDATE_PASSWORD(URL, data, UPDATE_PASSWORD_BEGIN, UPDATE_PASSWORD_SUCCESS, UPDATE_PASSWORD_ERROR);
}